name: deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read 
env: 
  AWS_REGION: "us-east-1"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.9.3 
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: shared-infra
          aws-region: ${{ env.AWS_REGION }}
      - name: terraform plan
        run: |
          cd terraform
          terraform init
          terraform plan -out tfplan
  terraform-apply:
    if: github.event_name == 'push'
    needs: terraform-plan
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.9.3 
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: shared-infra
          aws-region: ${{ env.AWS_REGION }}
      - name: terraform plan
        run: |
          cd terraform
          terraform init
          terraform plan -out tfplan
      - name: terraform apply
        run: |
          cd terraform
          terraform init
          terraform apply tfplan